// <auto-generated />
using System;
using Actividad_18.Server.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actividad_18.Server.Migrations
{
    [DbContext(typeof(ContextoConstructora))]
    [Migration("20230520065313_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Actividad_18.Shared.Models.Comandas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaF")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaI")
                        .HasColumnType("datetime2");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<int>("Id_Edificios")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Edificio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Trabajador2Id")
                        .HasColumnType("int");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int");

                    b.Property<int>("Trabajadores2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Trabajador2Id");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("Actividad_18.Shared.Models.Edificios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dirreccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Edificio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrabajadoresId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrabajadoresId");

                    b.ToTable("Edificios");
                });

            modelBuilder.Entity("Actividad_18.Shared.Models.Trabajadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Id_Sup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("Actividad_18.Shared.Models.Comandas", b =>
                {
                    b.HasOne("Actividad_18.Shared.Models.Trabajadores", "Trabajador2")
                        .WithMany("Comanda")
                        .HasForeignKey("Trabajador2Id");

                    b.Navigation("Trabajador2");
                });

            modelBuilder.Entity("Actividad_18.Shared.Models.Edificios", b =>
                {
                    b.HasOne("Actividad_18.Shared.Models.Trabajadores", "Trabajador")
                        .WithMany("Edificio")
                        .HasForeignKey("TrabajadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Actividad_18.Shared.Models.Trabajadores", b =>
                {
                    b.Navigation("Comanda");

                    b.Navigation("Edificio");
                });
#pragma warning restore 612, 618
        }
    }
}
